spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vip_admin?currentSchema=keycloak
    username: postgres
    password: postgres
  application:
    name: vip-svc-admin

server:
  port: 8001
  servlet.context-path: /vip

keycloak:
  url: http://localhost:5000/
  realm: acme
  client_id: acme-svc-admin
  secret: z14ludmSbdLv3bFsFFJjTdRBxLTQFoW9

openfga:
  url: http://127.0.0.1:8080
  store-id: 01KF0PNQ57NS1TTHAXG6ACJTD9