spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/vip_admin?currentSchema=vip_tenant
    username: postgres
    password: postgres
  application:
    name: vip-svc-admin
  servlet:
    multipart:
      file-size-threshold: 2MB

server:
  port: 8001
  servlet.context-path: /vip

keycloak:
  url: http://localhost:5000/
  client_id: vip-svc-admin
  secret: fck07p0G1mtYrWjZwyhftYNFRk1BBJqj

openfga:
  api-url: http://127.0.0.1:8080